language: php
php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
- 7.4
env:
  matrix:
  - dependencies=lowest
  - dependencies=highest
  global:
  - composer_flags="--no-interaction --no-ansi --no-progress --no-suggest --verbose"
before_install:
- composer self-update
- composer clear-cache
install:
- if [ -n "$GIT_HUB_TOKEN" ]; then composer config -g github-oauth.github.com "$GIT_HUB_TOKEN";
  fi;
- if [ "$dependencies" = "highest" ]; then composer update $composer_flags; fi;
- if [ "$dependencies" = "lowest" ]; then composer update $composer_flags --prefer-lowest
  --prefer-stable; fi;
script:
- vendor/bin/phpunit test/unit
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: mq6Wte5AYyRJQjMgf3kmvIKmixhgbMsX+vrbi6MeefpM9Pej2Db8+HvOeiJVw2WmcrYY+5RVxwIpRA7qojwrx2fy8RiARF8F472tRqI6Ku8zJHoxWtw/mIqletZ1IYRdCbCWeMzfCceon7JzWeBc+XiS5o/J+fgFuHbT3MX+yDTmd7dQmJ5hK56zhAZR38j3SStYpn/pp+af8q32n2GbHWF1UinrdQL+fqDDnFYoeRNOq4d96FPwM0wl0s5ZvmlIECDoKdPwFv/KlAuBmDWRYjew/gIFCcKY2mXv+JofyWCNPeMwKqP3h0LhjNqKIDVxongm4KUXrEkx+f9S/gw1NMoySL0M2hez7sEH7852J+qI+MkiP9A14HEz5dWxvxsYwrO6nDGci8Ag3Fwav13bGg9J4Y7RU8JPqMvzpbOxoKvr6U6KPAtL21yt+ta66CAiptUdo8wjqT8M8rFAlujN4ufOZgpmh0HlOTMyuPhxsRUThiFO1oedY8hod5Vr+AJE/cOYTk9raQP9uu2GOPanh3qJTTomPMf+c5sSNlu86gI8xc6VLStiSrmZpZ4lFE9IYT+0rrZXqYaaX9sKIvMjzbiCqw0bRSwtrwL8oszh5ATDVBvOgWNokBO+KVPFy6ULFlGwdoUmtmwY4iVy5nV75EJXvZnxxC/ms7fJ78d4a40=
